test_accounts:
  - username: luthien5921@gmail.com
    password: aichi@5921

  - username: luthien5921+shinsei1@gmail.com
    password: aichi@5921

  - username: luthien5921+shinsei2@gmail.com
    password: aichi@5921

  - username: giathanh010101@gmail.com
    password: aichi@5921

  - username: piechipiechipeach@gmail.com
    password: aichi@5921

  - username: piechipeach@gmail.com
    password: aichi@5921

  - username: nqkhanhtoan@gmail.com
    password: aichi@5921
    
dev_accounts:
  - username: nihahi50@gmail.com
    password: hoahong1234

  - username: ble79037@gmail.com
    password: hoahong1234

  # - username: benemmai380@gmail.com
  #   password: hoahong1234

  # - username: leongnardo12@gmail.com
  #   password: hoahong1234

  # - username: ngtrnghi123@gmail.com
  #   password: hoahong1234

  # - username: thanhvanngoc30@gmail.com
  #   password: hoahong1234

  # - username: davidalaba00000@gmail.com
  #   password: hoahong1234

  # - username: Nickpown0411@gmail.com
  #   password: hoahong1234

  # - username: marjyamada040493@gmail.com
  #   password: Marj0409

  # - username: Jamebrown0206@gmail.com
  #   password: hoahong1234

  # - username: hoahong2546@gmail.com   # false
  #   password: hoahong1234

  # - username: tuanminhnguyen1508@gmail.com   # false
  #   password: hoahong1234



  # - username: haronalcr7@gmail.com   # false
  #   password: hoahong1234

  # - username: tlica9443@gmail.com  # false
  #   password: hoahong1234

  # - username: tenkhongbiet293@gmail.com  # false
  #   password: hoahong1234
