customers:
  
  # - first_name: "Van Sang"
  #   last_name: "Phan"
  #   date_birth: "19970228"
  #   nation: "ベトナム"
  #   country: "ベトナム"

  # - first_name: "Hoai Phong"
  #   last_name: "Vo"
  #   date_birth: "19981101"
  #   nation: "ベトナム"
  #   country: "ベトナム"
  
  # - first_name: "Tuan Anh"
  #   last_name: "Huynh"
  #   date_birth: "19950106"
  #   nation: "ベトナム"
  #   country: "ベトナム"

  # - first_name: "Van Han"
  #   last_name: "Nguyen"
  #   date_birth: "19910525"
  #   nation: "ベトナム"
  #   country: "ベトナム"
  # - first_name: "The Hieu"
  #   last_name: "Truong"
  #   date_birth: "19990506"
  #   nation: "ベトナム"
  #   country: "ベトナム"

  # - first_name: "Xuan Truong"
  #   last_name: "Do"
  #   date_birth: "19921211"
  #   nation: "ベトナム"
  #   country: "ベトナム"

  # - first_name: "Anh Ngoc"
  #   last_name: "Chia"
  #   date_birth: "19961208"
  #   nation: "ベトナム"
  #   country: "ベトナム"
  
  

  



