# keyword: 行政
keyword: Hirabari
onlyday: true
debug_mode: true
max_num_retry: 10
default_num_threads: 4
display_number: 50
main_phone_number_dash: 080-1583-0891
uc: true
headless: false
timeout: 900
 